use_frameworks!

platform :ios, '8.0'

target 'TZSupreMarkBase_Example' do
  pod 'TZSupreMarkBase', :path => '../'

  target 'TZSupreMarkBase_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
